//#region Imports
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

import { TooltipProvider } from "@/components/ui/tooltip";
//#endregion

//#region Fonts
// Manrope cargada vía next/font/google. Expone CSS var `--font-manrope`
// para que Tailwind (ver globals.css → @theme.--font-manrope) la use.
const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });
//#endregion

//#region Metadata
// Metadata SEO/SSR por defecto del App Router.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//#endregion

//#region RootLayout
// Layout raíz. Orden de providers (de afuera hacia adentro):
//   ClerkProvider   → contexto auth en toda la app.
//   ThemeProvider   → dark/light mode (next-themes, attribute="class").
//   TooltipProvider → base-ui tooltips globales.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={cn("h-full", "antialiased", manrope.variable)}
        suppressHydrationWarning
      >
        <body className="min-h-full flex flex-col" suppressHydrationWarning>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TooltipProvider delayDuration={200}>{children}</TooltipProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
//#endregion
